name: Build container

on:
  push:
    branches:
      - master

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: login GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: generate tags
        id: tags
        run: |
          REF=${{ github.ref }}
          VERSION=${REF#refs/*/}

          TAGS="${{ github.repository }}:${VERSION}"
          TAGS="${TAGS},ghcr.io/${{ github.repository }}:${VERSION}"

          if [ ":${VERSION}:" != ":master:" ]; then
            TAGS="${TAGS},${{ github.repository }}:latest"
            TAGS="${TAGS},ghcr.io/${{ github.repository }}:latest"
          fi

          echo "::set-output name=TAGS::${TAGS}"
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.tags.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
