name: Test and Build

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15.x

      - uses: actions/checkout@v1
        with:
          path: go/src/github.com/macrat/landns

      - name: Download libraries
        run: go get -d -v github.com/macrat/landns
        env:
          GOPATH: /home/runner/work/landns/go

      - name: Test
        run: go test -v -cover -covermode=count -coverprofile=coverage.txt ./...
        env:
          GOPATH: /home/runner/work/landns/go

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: Test
    if: "${{ github.event_name == 'push' }}"
    steps:
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: login GitHub container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: generate tags
        id: tags
        run: |
          TAGS="${{ github.repository }}:latest"
          TAGS="${TAGS},ghcr.io/${{ github.repository }}:latest"
          TAGS="${TAGS},${{ github.repository }}:${{ github.sha }}"
          TAGS="${TAGS},ghcr.io/${{ github.repository }}:${{ github.sha }}"
          echo "::set-output name=TAGS::${TAGS}"
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.tags.outputs.TAGS }}
          platforms: linux/amd64,linux/arm64,linux/arm/v6,linux/arm/v7
