name: Test and Build

on: 
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - uses: actions/checkout@v1
        with:
          path: go/src/github.com/macrat/landns

      - name: Download libraries
        run: go get -d -v github.com/macrat/landns
        env:
          GOPATH: /home/runner/work/landns/go

      - name: Test
        run: go test -v -cover -covermode=count -coverprofile=coverage.txt ./...
        env:
          GOPATH: /home/runner/work/landns/go

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - uses: actions/checkout@v1

      - name: Download libraries
        run: go get -t -d -v ./...

      - name: Build server
        run: go build -v
