name: Test and Build

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - uses: actions/checkout@v1

      - name: Download libraries
        run: go get -t -d -v ./...

      - name: Test
        run: go test -v -cover -coverprofile=coverage.txt ./...

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - uses: actions/checkout@v1

      - name: Download libraries
        run: go get -t -d -v ./...

      - name: Build server
        run: go build -v

      - name: Build client
        run: go build -o ctl ./landnsctl
